"""Shared helpers for building KDP-ready kids' books (interiors + full-wrap covers).

All artwork is generated by code, so every page is original and owned by the
publisher: no licensed characters, no third-party images, no AI images.
"""
import math
import random

from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas as rl_canvas

# ---- Publisher settings: change these before uploading -----------------------
AUTHOR = "Prince Asamoah"
YEAR = 2026

# ---- KDP print specs (US, 8.5 x 11 in, white paper, no interior bleed) --------
TRIM_W, TRIM_H = 8.5 * inch, 11 * inch
MARGIN = 0.6 * inch            # safely above KDP's 0.375" gutter / 0.25" outside minimum
COVER_BLEED = 0.125 * inch
SPINE_PER_PAGE_WHITE = 0.002252 * inch
MIN_PAGES_FOR_SPINE_TEXT = 79

FONT_DIR = "/usr/share/fonts/truetype/"
pdfmetrics.registerFont(TTFont("Bold", FONT_DIR + "dejavu/DejaVuSans-Bold.ttf"))
pdfmetrics.registerFont(TTFont("Regular", FONT_DIR + "dejavu/DejaVuSans.ttf"))
pdfmetrics.registerFont(TTFont("Round", FONT_DIR + "liberation/LiberationSans-Bold.ttf"))
pdfmetrics.registerFont(TTFont("Mono", FONT_DIR + "dejavu/DejaVuSansMono-Bold.ttf"))

INK = HexColor("#1b1b1b")
LIGHT = HexColor("#9a9a9a")


def new_interior(path, title):
    c = rl_canvas.Canvas(path, pagesize=(TRIM_W, TRIM_H))
    c.setTitle(title)
    c.setAuthor(AUTHOR)
    return c


def fit_font_size(text, font, max_size, max_width):
    size = max_size
    while size > 6 and pdfmetrics.stringWidth(text, font, size) > max_width:
        size -= 0.5
    return size


def centered(c, text, y, font="Bold", size=24, color=INK, x=None, max_width=None):
    if max_width:
        size = fit_font_size(text, font, size, max_width)
    c.setFont(font, size)
    c.setFillColor(color)
    c.drawCentredString(TRIM_W / 2 if x is None else x, y, text)
    return size


def outlined_text(c, text, x, y, font, size, fill, stroke, stroke_w, align="center"):
    w = pdfmetrics.stringWidth(text, font, size)
    if align == "center":
        x -= w / 2
    c.saveState()
    t = c.beginText(x, y)
    t.setFont(font, size)
    t.setTextRenderMode(1)
    c.setStrokeColor(stroke)
    c.setLineWidth(stroke_w)
    c.setLineJoin(1)
    t.textLine(text)
    c.drawText(t)
    c.restoreState()
    c.setFont(font, size)
    c.setFillColor(fill)
    c.drawString(x, y, text)


def star_path(c, cx, cy, r_out, r_in, points=5, rot=90):
    p = c.beginPath()
    for i in range(points * 2):
        r = r_out if i % 2 == 0 else r_in
        a = math.radians(rot + i * 180 / points)
        x, y = cx + r * math.cos(a), cy + r * math.sin(a)
        (p.moveTo if i == 0 else p.lineTo)(x, y)
    p.close()
    return p


def heart_path(c, cx, cy, s):
    p = c.beginPath()
    p.moveTo(cx, cy - s)
    p.curveTo(cx - 1.4 * s, cy - 0.1 * s, cx - 0.9 * s, cy + 1.0 * s, cx, cy + 0.45 * s)
    p.curveTo(cx + 0.9 * s, cy + 1.0 * s, cx + 1.4 * s, cy - 0.1 * s, cx, cy - s)
    p.close()
    return p


# ---- Front matter -------------------------------------------------------------

def frame(c, color=INK, width=3, radius=18, inset=None):
    inset = MARGIN if inset is None else inset
    c.setStrokeColor(color)
    c.setLineWidth(width)
    c.roundRect(inset, inset, TRIM_W - 2 * inset, TRIM_H - 2 * inset, radius, stroke=1, fill=0)


def title_page(c, title_lines, subtitle):
    frame(c)
    y = TRIM_H * 0.66
    for line in title_lines:
        centered(c, line, y, size=40, max_width=TRIM_W - 2.2 * MARGIN)
        y -= 50
    centered(c, subtitle, y - 10, font="Regular", size=16, max_width=TRIM_W - 2.4 * MARGIN)
    for i, dx in enumerate((-1.2, 0, 1.2)):
        c.setLineWidth(2.5)
        c.setStrokeColor(INK)
        c.drawPath(star_path(c, TRIM_W / 2 + dx * inch, TRIM_H * 0.32, 26 if i == 1 else 18, 11 if i == 1 else 8))
    centered(c, AUTHOR, MARGIN + 0.9 * inch, font="Regular", size=14)
    c.showPage()


def copyright_page(c, title):
    lines = [
        title,
        "",
        f"Copyright © {YEAR} {AUTHOR}. All rights reserved.",
        "",
        "No part of this book may be reproduced, stored, or transmitted in any",
        "form or by any means without written permission from the publisher,",
        "except that the purchaser may photocopy pages for personal or single-",
        "classroom use.",
        "",
        "All puzzles and illustrations in this book are original works.",
    ]
    y = MARGIN + 3.2 * inch
    for line in lines:
        centered(c, line, y, font="Regular", size=10)
        y -= 15
    c.showPage()


def belongs_to_page(c):
    frame(c, width=4, radius=30)
    centered(c, "This Book", TRIM_H * 0.68, size=48)
    centered(c, "Belongs To", TRIM_H * 0.68 - 60, size=48)
    c.setLineWidth(2)
    c.setStrokeColor(INK)
    c.line(TRIM_W * 0.2, TRIM_H * 0.42, TRIM_W * 0.8, TRIM_H * 0.42)
    c.setLineWidth(2.5)
    for dx, s in ((-1.6, 30), (0, 38), (1.6, 30)):
        c.drawPath(heart_path(c, TRIM_W / 2 + dx * inch, TRIM_H * 0.26, s))
    c.showPage()


def certificate_page(c, heading, body):
    frame(c, width=4, radius=10)
    frame(c, width=1.5, radius=6, inset=MARGIN + 10)
    centered(c, "CERTIFICATE", TRIM_H * 0.78, size=44)
    centered(c, "OF ACHIEVEMENT", TRIM_H * 0.78 - 44, size=26)
    centered(c, "This is to certify that", TRIM_H * 0.6, font="Regular", size=18)
    c.setLineWidth(1.5)
    c.line(TRIM_W * 0.2, TRIM_H * 0.5, TRIM_W * 0.8, TRIM_H * 0.5)
    centered(c, heading, TRIM_H * 0.42, size=22, max_width=TRIM_W - 3 * MARGIN)
    centered(c, body, TRIM_H * 0.42 - 30, font="Regular", size=16, max_width=TRIM_W - 3 * MARGIN)
    c.setLineWidth(2.5)
    c.drawPath(star_path(c, TRIM_W / 2, TRIM_H * 0.22, 60, 26))
    c.setFont("Regular", 12)
    c.line(TRIM_W * 0.15, MARGIN + 0.9 * inch, TRIM_W * 0.4, MARGIN + 0.9 * inch)
    c.line(TRIM_W * 0.6, MARGIN + 0.9 * inch, TRIM_W * 0.85, MARGIN + 0.9 * inch)
    c.drawCentredString(TRIM_W * 0.275, MARGIN + 0.6 * inch, "Date")
    c.drawCentredString(TRIM_W * 0.725, MARGIN + 0.6 * inch, "Signed")
    c.showPage()


def pad_to_even(c, page_count):
    """KDP needs an even page count; add a blank last page when required."""
    if page_count % 2:
        c.showPage()
        page_count += 1
    return page_count


# ---- Covers -------------------------------------------------------------------

def cover_size(page_count):
    spine = page_count * SPINE_PER_PAGE_WHITE
    return 2 * COVER_BLEED + 2 * TRIM_W + spine, 2 * COVER_BLEED + TRIM_H, spine


def make_cover(path, page_count, *, title_lines, subtitle, badge, blurb, bullets,
               bg, accent, title_fill, art, seed=1):
    """Full-wrap paperback cover (back | spine | front) with bleed, per KDP template."""
    W, H, spine = cover_size(page_count)
    c = rl_canvas.Canvas(path, pagesize=(W, H))
    c.setTitle(" ".join(title_lines))
    c.setAuthor(AUTHOR)
    rnd = random.Random(seed)
    bg, accent, title_fill = HexColor(bg), HexColor(accent), HexColor(title_fill)

    c.setFillColor(bg)
    c.rect(0, 0, W, H, stroke=0, fill=1)

    # Confetti across the whole wrap
    c.saveState()
    c.setFillColor(white)
    c.setFillAlpha(0.18)
    for _ in range(90):
        x, y = rnd.uniform(0, W), rnd.uniform(0, H)
        r = rnd.uniform(6, 18)
        if rnd.random() < 0.5:
            c.drawPath(star_path(c, x, y, r, r * 0.45, rot=rnd.uniform(0, 72)), stroke=0, fill=1)
        else:
            c.circle(x, y, r * 0.6, stroke=0, fill=1)
    c.restoreState()

    back_x = COVER_BLEED
    front_x = COVER_BLEED + TRIM_W + spine
    safe = 0.5 * inch
    cy_base = COVER_BLEED

    # ---- Front ----
    fx0, fx1 = front_x + safe, front_x + TRIM_W - safe
    fw = fx1 - fx0
    y = cy_base + TRIM_H - safe - 0.9 * inch
    size = min(fit_font_size(l, "Bold", 78, fw) for l in title_lines)
    for line in title_lines:
        outlined_text(c, line, (fx0 + fx1) / 2, y, "Bold", size, title_fill, INK, 9)
        y -= size * 1.05
    sub_size = fit_font_size(subtitle, "Bold", 24, fw - 20)
    c.setFillColor(white)
    c.roundRect(fx0 + 10, y - 16, fw - 20, sub_size + 22, 14, stroke=0, fill=1)
    c.setFillColor(INK)
    c.setFont("Bold", sub_size)
    c.drawCentredString((fx0 + fx1) / 2, y - 6, subtitle)

    art_top = y - 40
    art_bottom = cy_base + safe + 1.55 * inch
    art(c, fx0 + 0.3 * inch, art_bottom, fw - 0.6 * inch, art_top - art_bottom, accent)

    # Age badge
    bx, by = fx1 - 0.8 * inch, cy_base + safe + 0.75 * inch
    c.setFillColor(accent)
    c.setStrokeColor(INK)
    c.setLineWidth(4)
    c.drawPath(star_path(c, bx, by, 64, 47, points=12), stroke=1, fill=1)
    c.setFillColor(white)
    for i, line in enumerate(badge):
        c.setFont("Bold", 20 if i == 0 else 15)
        c.drawCentredString(bx, by + 6 - i * 20, line)

    c.setFont("Bold", 18)
    c.setFillColor(white)
    c.drawCentredString((fx0 + fx1) / 2, cy_base + safe, AUTHOR)

    # ---- Spine ----
    if page_count >= MIN_PAGES_FOR_SPINE_TEXT:
        sx = COVER_BLEED + TRIM_W + spine / 2
        c.saveState()
        c.translate(sx, cy_base + TRIM_H / 2)
        c.rotate(-90)
        text = " ".join(title_lines)
        s = min(spine * 0.55 / (1 * inch) * 72, 16)
        s = fit_font_size(text + "   " + AUTHOR, "Bold", s, TRIM_H - 1.5 * inch)
        c.setFont("Bold", s)
        c.setFillColor(white)
        c.drawCentredString(0, -s * 0.35, f"{text}   •   {AUTHOR}")
        c.restoreState()

    # ---- Back ----
    bx0, bx1 = back_x + safe, back_x + TRIM_W - safe
    panel_top = cy_base + TRIM_H - safe
    panel_bottom = cy_base + safe + 1.6 * inch
    c.setFillColor(white)
    c.roundRect(bx0, panel_bottom, bx1 - bx0, panel_top - panel_bottom, 24, stroke=0, fill=1)
    ty = panel_top - 0.75 * inch
    head = " ".join(title_lines)
    c.setFillColor(INK)
    c.setFont("Bold", fit_font_size(head, "Bold", 30, bx1 - bx0 - 0.6 * inch))
    c.drawCentredString((bx0 + bx1) / 2, ty, head)
    ty -= 0.55 * inch
    c.setFont("Regular", 18)
    for line in blurb:
        c.drawCentredString((bx0 + bx1) / 2, ty, line)
        ty -= 25
    ty -= 12
    for b in bullets:
        c.setFillColor(accent)
        c.drawPath(star_path(c, bx0 + 0.55 * inch, ty + 5, 9, 4), stroke=0, fill=1)
        c.setFillColor(INK)
        c.setFont("Bold", 18)
        c.drawString(bx0 + 0.8 * inch, ty, b)
        ty -= 30
    # Small sample of the inside art fills the rest of the panel
    if ty - panel_bottom > 1.6 * inch:
        art(c, bx0 + 0.5 * inch, panel_bottom + 0.35 * inch,
            bx1 - bx0 - 1.0 * inch, ty - panel_bottom - 0.6 * inch, accent)
    # KDP prints the barcode here (2" x 1.2" white box, bottom right of back cover)
    c.showPage()
    c.save()
    return W, H, spine
